RegressionRAM
std::vector<int> RegressionRAM::mapping
Mapeamento da RAM.
Referenced by getIndex, getJSON, getMapping, getsizeoff, RegressionRAM, ~RegressionRAM.
regression_ram_t RegressionRAM::memory
Memória da RAM.
Referenced by applyFit, calculateFit, getJSON, getMemory, getsizeoff, getVote, RegressionRAM, train, ~RegressionRAM.
int RegressionRAM::minOne
Número mínimo de uns.
Referenced by getIndex, getJSON, RegressionRAM, setMinOne.
int RegressionRAM::minZero
Número mínimo de zeros.
Referenced by getIndex, getJSON, RegressionRAM, setMinZero.
void RegressionRAM::applyFit()
Aplica o ajuste calculado.
References memory.
void RegressionRAM::calculateFit(const BinInput &image, const double yFit)
Calcula o ajuste da RAM para a imagem binária e o valor yFit.
image Imagem binária. yFit Valor de ajuste.
References getIndex, memory.
nl::json RegressionRAM::getJSON() const
Obtém a configuração da RAM em formato JSON.
Objeto JSON representando a configuração da RAM.
References mapping, memory, minOne, minZero.
std::vector< int > RegressionRAM::getMapping() const
Obtém o mapeamento da RAM.
Vetor de inteiros representando o mapeamento.
References mapping.
regression_ram_t RegressionRAM::getMemory() const
Obtém a memória da RAM.
Memória da RAM.
References memory.
long RegressionRAM::getsizeoff() const
Obtém o tamanho da RAM em bytes.
Tamanho da RAM em bytes.
References mapping, memory, RegressionRAM.
regression_content_t RegressionRAM::getVote(const BinInput &image) const
Obtém o voto da RAM para a imagem binária fornecida.
image Imagem binária. Conteúdo da RAM associado à imagem.
References getIndex, memory.
RegressionRAM::RegressionRAM()
Construtor padrão.
Referenced by getsizeoff.
RegressionRAM::RegressionRAM(const std::vector< int > mapping, const int minZero=0, const int minOne=0)
Construtor da classe que inicializa a RAM com parâmetros específicos.
mapping Vetor de inteiros representando o mapeamento. minZero Número mínimo de zeros. minOne Número mínimo de uns.
RegressionRAM::RegressionRAM(nl::json c)
Construtor da classe que inicializa a RAM com um objeto JSON.
c Objeto do tipo nl::json contendo a configuração inicial da RAM.
References RegressionRAMDataHandle::get, mapping, memory, minOne, minZero.
void RegressionRAM::setMinOne(const int value)
Define o valor mínimo de uns.
value Valor mínimo de uns.
References minOne.
void RegressionRAM::setMinZero(const int value)
Define o valor mínimo de zeros.
value Valor mínimo de zeros.
References minZero.
void RegressionRAM::train(const BinInput &image, const double y)
Treina a RAM com a imagem binária e o valor y.
image Imagem binária utilizada para o treinamento. y Valor associado à imagem.
References getIndex, memory.
RegressionRAM::~RegressionRAM()
Destrutor da classe que limpa a memória.
References mapping, memory.
std::tuple< addr_t, bool > RegressionRAM::getIndex(const BinInput &image) const
Obtém o índice da imagem binária.
image Imagem binária. Tupla contendo o índice e um booleano indicando se os critérios mínimos foram atendidos.
References mapping, minOne, minZero.
Referenced by calculateFit, getVote, train.