RegressionRAMDataHandle
std::unordered_map<int, regression_ram_t> RegressionRAMDataHandle::ramdata
Container for the RAM data.
Referenced by compare, data, data, get, get, RegressionRAMDataHandle, RegressionRAMDataHandle, save, set, set, setData.
bool RegressionRAMDataHandle::compare(RegressionRAMDataHandle &other)
Compares this object with another RegressionRAMDataHandle object.
other The other RegressionRAMDataHandle object to compare with. True if both objects are equal, otherwise false.
References ramdata.
std::string RegressionRAMDataHandle::data()
Gets the entire data as a string.
The entire data as a string.
References data, ramdata.
Referenced by data, RegressionRAMDataHandle, RegressionRAMDataHandle, save.
std::string RegressionRAMDataHandle::data(int r)
Gets the data of a specific RAM as a string.
r The RAM index. The data of the specified RAM as a string.
References ramdata.
regression_ram_t RegressionRAMDataHandle::get(int r)
Gets the entire content of a specific RAM.
r The RAM index. The entire RAM content.
References ramdata.
regression_content_t RegressionRAMDataHandle::get(int r, int addr)
Gets the content of a specific RAM at a specific address.
r The RAM index. addr The address within the RAM. The content at the specified RAM and address.
References ramdata.
Referenced by RegressionRAM::RegressionRAM.
RegressionRAMDataHandle::RegressionRAMDataHandle()
Default constructor.
RegressionRAMDataHandle::RegressionRAMDataHandle(regression_ram_t data)
Constructor that initializes the object with a single regression RAM data.
data A single regression RAM data.
References data, ramdata.
RegressionRAMDataHandle::RegressionRAMDataHandle(std::string inputdata)
Constructor that initializes the object with input data.
inputdata The input data as a string.
References setData.
RegressionRAMDataHandle::RegressionRAMDataHandle(std::vector< regression_ram_t > data)
Constructor that initializes the object with multiple regression RAM data.
data A vector containing multiple regression RAM data.
References data, ramdata.
void RegressionRAMDataHandle::save(std::string prefix)
Saves the data to a file with a given prefix.
prefix The prefix for the filename.
References data, ramdata.
void RegressionRAMDataHandle::set(int r, int addr, regression_content_t value)
Sets the content at a specific RAM and address.
r The RAM index. addr The address within the RAM. value The value to set at the specified RAM and address.
References ramdata.
void RegressionRAMDataHandle::set(int r, regression_ram_t value)
Sets the entire content of a specific RAM.
r The RAM index. value The value to set for the specified RAM.
References ramdata.
regression_ram_t RegressionRAMDataHandle::dataToRam(const std::string &inputdata)
Converts a string to RAM data.
inputdata The input data as a string. The converted RAM data.
Referenced by setData.
void RegressionRAMDataHandle::setData(std::string inputdata)
Sets the data from an input string.
inputdata The input data as a string.
References dataToRam, ramdata.
Referenced by RegressionRAMDataHandle.