RegressionWisard
int RegressionWisard::addressSize
Tamanho do endereço.
Referenced by checkAddressSize, checkMinZeroOne, RegressionWisard, setRAMShuffle.
bool RegressionWisard::completeAddressing
Endereçamento completo.
Referenced by RegressionWisard, setRAMShuffle.
int RegressionWisard::entrySize
Tamanho da entrada.
Referenced by checkAddressSize, checkEntrySize, RegressionWisard, setRAMShuffle.
std::vector<int> RegressionWisard::mapping
Mapeamento dos índices.
Referenced by RegressionWisard, setRAMShuffle.
Mean* RegressionWisard::mean
Objeto para cálculo de média.
Referenced by predict.
int RegressionWisard::minOne
Número mínimo de uns.
Referenced by RegressionWisard, setRAMShuffle.
int RegressionWisard::minZero
Número mínimo de zeros.
Referenced by RegressionWisard, setRAMShuffle.
int RegressionWisard::numberOfTrainings
Número de treinamentos.
Referenced by RegressionWisard, train.
bool RegressionWisard::orderedMapping
Mapeamento ordenado.
Referenced by RegressionWisard, setRAMShuffle.
std::vector<RegressionRAM> RegressionWisard::rams
Vetor de RAMs de regressão.
Referenced by applyFit, calculateFit, predict, RegressionWisard, setRAMShuffle, train, ~RegressionWisard.
int RegressionWisard::steps
Número de passos.
Referenced by RegressionWisard, train.
void RegressionWisard::applyFit()
Aplica o ajuste calculado.
References rams.
Referenced by train.
void RegressionWisard::calculateFit(const BinInput &input, const double y)
Calcula o ajuste para uma entrada binária e um valor y.
input Entrada binária. y Valor associado à entrada.
References predict, rams.
Referenced by train.
double RegressionWisard::predict(const BinInput &input) const
Faz a predição para uma entrada binária.
input Entrada binária. O valor predito.
References Mean::calculate, checkEntrySize, mean, rams.
Referenced by calculateFit, predict.
std::vector< double > RegressionWisard::predict(const DataSet &dataset) const
Faz a predição para um conjunto de dados.
dataset Conjunto de dados. Vetor com os valores preditos.
References predict.
RegressionWisard::RegressionWisard()
Construtor padrão.
RegressionWisard::RegressionWisard(int addressSize)
Construtor que inicializa o modelo com um tamanho de endereço especificado.
addressSize Tamanho do endereço.
RegressionWisard::RegressionWisard(nl::json c)
Construtor que inicializa o modelo com um objeto JSON.
c Objeto do tipo nl::json contendo a configuração inicial do modelo.
References addressSize, completeAddressing, entrySize, mapping, minOne, minZero, numberOfTrainings, orderedMapping, rams, steps.
void RegressionWisard::train(const BinInput &input, const double y)
Treina o modelo com uma entrada binária e um valor y.
input Entrada binária. y Valor associado à entrada.
References checkEntrySize, numberOfTrainings, rams, setRAMShuffle.
void RegressionWisard::train(const DataSet &dataset)
Treina o modelo com um conjunto de dados.
dataset Conjunto de dados utilizado para o treinamento.
References applyFit, calculateFit, steps, train.
Referenced by train.
RegressionWisard::~RegressionWisard()
Destrutor da classe que limpa a memória.
References rams.
void RegressionWisard::checkAddressSize(const int entrySize, const int addressSize) const
Verifica o tamanho do endereço.
entrySize Tamanho da entrada. addressSize Tamanho do endereço.
References addressSize, entrySize.
Referenced by setRAMShuffle.
void RegressionWisard::checkEntrySize(const int entry) const
Verifica o tamanho da entrada.
entry Tamanho da entrada.
References entrySize.
Referenced by predict, train.
void RegressionWisard::checkMinZeroOne(int min0, int min1)
Verifica os valores mínimos de zeros e uns.
min0 Valor mínimo de zeros. min1 Valor mínimo de uns.
References addressSize.
void RegressionWisard::setRAMShuffle(int entrySize)
Configura o embaralhamento das RAMs.
entrySize Tamanho da entrada.
References addressSize, checkAddressSize, completeAddressing, entrySize, mapping, minOne, minZero, orderedMapping, rams.
Referenced by train.