.TH "Referência do diretório src/models/wisard" 3 "Version 2.0" "WISARD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório src/models/wisard
.SH SYNOPSIS
.br
.PP
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBdiscriminator\&.cc\fP"
.br
.ti -1c
.RI "ficheiro \fBwisard\&.cc\fP"
.br
.in -1c
