.TH "src/models/wisard/discriminator.cc" 3 "Version 2.0" "WISARD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models/wisard/discriminator.cc
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <random>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <vector>\fP
.br
\fR#include '\&.\&./\&.\&./\&.\&./include/bitarray\&.h'\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBDiscriminator\fP"
.br
.RI "A class to implement a discriminator using bit arrays and pseudo-random mappings\&. "
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para WISARD a partir do código fonte\&.
