.TH "md_src_2models_2regressionwisard_2sequence" 3 "Version 2.0" "WISARD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_2models_2regressionwisard_2sequence \- sequence 
.PP
*meanfunctions *regressionramdatahandle *regressionram *regressionwisard
.PP
steps? artigo wisard; https://github.com/IAZero/wisardpkg/tree/c51b395c0e85ae007bb7f8699515a3136356ef65 
