.TH "src/models/regressionwisard/meanfunctions.cc" 3 "Version 2.0" "WISARD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models/regressionwisard/meanfunctions.cc
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBHarmonicMean\fP"
.br
.RI "Classe para cálculo de média harmônica\&. "
.ti -1c
.RI "class \fBMean\fP"
.br
.RI "Classe base abstrata para cálculo de médias\&. "
.ti -1c
.RI "class \fBMedian\fP"
.br
.RI "Classe para cálculo de mediana\&. "
.ti -1c
.RI "class \fBPowerMean\fP"
.br
.RI "Classe para cálculo de média de potência\&. "
.ti -1c
.RI "class \fBSimpleMean\fP"
.br
.RI "Classe para cálculo de média simples\&. "
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para WISARD a partir do código fonte\&.
