.TH "src/models/regressionwisard/regressionwisard.cc" 3 "Version 2.0" "WISARD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models/regressionwisard/regressionwisard.cc
.SH SYNOPSIS
.br
.PP
.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBRegressionWisard\fP"
.br
.RI "Classe para um modelo de regressão utilizando \fBWisard\fP\&. "
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para WISARD a partir do código fonte\&.
