.TH "src/models/wisard/wisard.cc" 3 "Version 2.0" "WISARD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models/wisard/wisard.cc
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include 'discriminator\&.cc'\fP
.br
\fR#include <array>\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBWisard\fP"
.br
.RI "A class to implement the \fBWisard\fP algorithm using multiple discriminators\&. "
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para WISARD a partir do código fonte\&.
